version: '3'

services:
  docker-mysql:
    image: 'mariadb'
    ports:
    - "5306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=Welcome123
           - MYSQL_DATABASE=ps_climbers_docker
           - MYSQL_PASSWORD=Welcome123
           - MYSQL_ROOT_HOST=%
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost", "-pWelcome123"]
           timeout: 20s
           retries: 10
  backendserver:
    build: .
    #image: 'dejanostojic/diplomski-be:init.test.0.0.1'
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/ps_climbers_docker?useLegacyDatetimeCode=false&serverTimezone=UTC
    - MYSQL_USER=root
    - MYSQL_PASS=Welcome123
    - spring.jpa.generate-ddl=false
    - spring.jpa.hibernate.ddl-auto=none
    - spring.datasource.initialization-mode=always
    ports:
    - "9081:8081"
    links:
    - "docker-mysql"
    depends_on:
    - "docker-mysql"
    restart: always
  frontend:
    #build: ../diplomski-fe/
    image: 'dejanostojic/diplomski-fe:init.local.0.0.5'
    links:
    - "backendserver"
    depends_on:
    - "backendserver"
    ports:
    - "4200:4200"